#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -i $in.1 -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in.1 -s 1 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -i $in.1 -s 1 -k ORGANISM,SEQ,COUNT -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -i $in.1 -s 1 -c 2,1 -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -i $in.1 -s 1 -c 2,1 -k COUNT,SEQ -O $tmp"
assert_no_diff $tmp $out.5
clean

run "$bp -i $in.2 -O $tmp"
assert_no_diff $tmp $out.6
clean

run "$bp -i $in.2 -n 1 -O $tmp"
assert_no_diff $tmp $out.7
clean

run "$bp -i $in.3 -d ';' -O $tmp"
assert_no_diff $tmp $out.8
clean
