#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -I $in -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -c 0 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -h -O $tmp"
assert_no_diff $tmp $out.3
clean
