#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -I $in -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -m 3 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -m 3 -l 1 -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in -m 3 -L -O $tmp"
assert_no_diff $tmp $out.4
clean
