#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -I $in -k SEQ -s A -r n -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -k SEQ_NAME -d Tt -O $tmp"
assert_no_diff $tmp $out.2
clean
