#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -I $in.1 -r -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in.1 -rg -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in.1 -rgb $in.2 -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in.1 -p 4 -r -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -I $in.1 -p 4 -rg -O $tmp"
assert_no_diff $tmp $out.5
clean

run "$bp -I $in.1 -p 4 -rgb $in.2 -O $tmp"
assert_no_diff $tmp $out.6
clean

run "$bp -I $in.1 -p 4 -m 1 -r -O $tmp"
assert_no_diff $tmp $out.7
clean

run "$bp -I $in.1 -p 4 -m 1 -rg -O $tmp"
assert_no_diff $tmp $out.8
clean

run "$bp -I $in.1 -p 4 -m 1 -rgb $in.2 -O $tmp"
assert_no_diff $tmp $out.9
clean

run "$bp -I $in.1 -p 4 -m 2 -r -O $tmp"
assert_no_diff $tmp $out.10
clean

run "$bp -I $in.1 -p 4 -m 2 -rg -O $tmp"
assert_no_diff $tmp $out.11
clean

run "$bp -I $in.1 -p 4 -m 2 -rgb $in.2 -O $tmp"
assert_no_diff $tmp $out.12
clean

run "$bp -I $in.1 -p 4 -m 2 -Rrg -O $tmp"
assert_no_diff $tmp $out.13
clean
