#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -I $in -s '\d' -r '' -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -k SEQ -s 'n' -r '' -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -k SEQ -s 'n' -r '' -i -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in -k SEQ -s 'n' -r '' -i -g -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -I $in -k SEQ -s 'n{3,}' -r '' -i -g -O $tmp"
assert_no_diff $tmp $out.5
clean
