#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -I $in -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -C 2 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -i 1 -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in -i 1 -c -O $tmp"
assert_no_diff $tmp $out.4
clean
