#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -I $in -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -s 'GTG' -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -S 'TAA' -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in -m 700 -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -I $in -M 100 -O $tmp"
assert_no_diff $tmp $out.5
clean

run "$bp -I $in -n -O $tmp"
assert_no_diff $tmp $out.6
clean
