#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -I $in -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -l -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -l -w 10 -O $tmp"
assert_no_diff $tmp $out.3
clean
