#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -I $in -d $in.db -i 1 -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in -d $in.db -i 1 -p local -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in -d $in.db -i 0.99 -e 0.1 -p local -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in -d $in.db -i 0.99 -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -I $in -d $in.db -i 1 -m 1 -O $tmp"
assert_no_diff $tmp $out.5
clean
