#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -i $in.1 -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in.1 -e base_33 -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in.2 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -i $in.2 -e base_64 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -i $in.1.gz -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in.1 -n 1 -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -i $in.3 -j $in.4 -O $tmp"
assert_no_diff $tmp $out.4
clean
