#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run_quiet "create_blast_index -I $in.1 -d $tmp_dir -i 'nucleotide' -x"
run_quiet "create_blast_index -I $in.3 -d $tmp_dir -i 'protein' -x"

run "$bp -I $in.2 -d $tmp_dir/nucleotide -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in.2 -d $tmp_dir/protein -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in.4 -d $tmp_dir/nucleotide -O $tmp"
assert_no_diff $tmp $out.3
clean

run "$bp -I $in.4 -d $tmp_dir/protein -O $tmp"
assert_no_diff $tmp $out.4
clean

run "$bp -I $in.2 -d $tmp_dir/nucleotide -p tblastx -O $tmp"
assert_no_diff $tmp $out.5
clean

rm -rf $tmp_dir
