#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -i $in -q $in.qual -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in.gz -q $in.qual.gz -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in -q $in.qual -n 1 -O $tmp"
assert_no_diff $tmp $out.2
clean
