#!/bin/bash

source "$BP_DIR/tests/lib/test.sh"

run "$bp -I $in.1 -k SEQ_NAME -s test1 -r foo -O $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -I $in.1 -k SEQ_NAME -f $in.2 -O $tmp"
assert_no_diff $tmp $out.2
clean

run "$bp -I $in.1 -k SEQ_NAME -f $in.2 -S 2 -R 1 -O $tmp"
assert_no_diff $tmp $out.3
clean
