#!/bin/bash

source "$BP_DIR/bp_test/lib/test.sh"

run "$bp -i $in -o $tmp"
assert_no_diff $tmp $out.1
clean

run "$bp -i $in -O $tmp --method=atom -M"
assert_no_diff $tmp $out.2
clean

run "$bp -i $in -o $tmp -m seqres -c atom -a CA -r ILE,SER"
assert_no_diff $tmp $out.3
clean
